version: "3"
services:
  frontend:
    build: ./frontend
    container_name: timanttipeli-frontend
    
  server:
    build: ./backend
    container_name: timanttipeli-server
  
  proxy:
    image: nginx:alpine
    container_name: timanttipeli-proxy
    ports:
    - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - server