services:
    frontend:
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
        container_name: timanttipeli-frontend
        ports:
            - 5000:80

    backend:
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        container_name: timanttipeli-backend

    proxy:
        image: nginx:alpine
        container_name: timanttipeli-proxy
        ports:
            - 8080:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - frontend
            - backend
